import turtle 
turtle.setup(640,480)
# Drawing a rectangle
turtle.forward(100)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(50)
turtle.reset()

# Box with pause
turtle.forward(20)
turtle.penup()
turtle.forward(10)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(10)
turtle.pendown()
turtle.forward(20)
turtle.right(90)
turtle.forward(20)
turtle.penup()
turtle.forward(10)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(10)
turtle.pendown()
turtle.forward(20)
turtle.reset()




# Drawing circle
turtle.circle(50)
turtle.forward(10)
turtle.pencolor("red")
turtle.circle(60)
turtle.forward(10)
turtle.pencolor("blue")
turtle.width(5)
turtle.circle(70)
turtle.forward(10)
turtle.pencolor("green")
turtle.width(7)
turtle.fillcolor("purple")
turtle.begin_fill()
turtle.circle(80)
turtle.end_fill()
turtle.reset()

# Drawing circles with go function
turtle.circle(30)
turtle.penup()
turtle.goto(130, 130)
turtle.pendown()
turtle.circle(20)
turtle.reset()

# Drawing Olympic flag. color of the circles are blue, yellow, balck, green, red
turtle.goto(0, 0)
turtle.pendown()
turtle.pencolor("black")
turtle.circle(50)
turtle.penup()
turtle.goto(-120, 0)
turtle.pendown()
turtle.pencolor("blue")
turtle.circle(50)
turtle.penup()
turtle.goto(120, 0)
turtle.pendown()
turtle.pencolor("red")
turtle.circle(50)
turtle.penup()
turtle.goto(-60, -50)
turtle.pendown()
turtle.pencolor("yellow")
turtle.circle(50)
turtle.penup()
turtle.goto(60, -50)
turtle.pendown()
turtle.pencolor("green")
turtle.circle(50)


turtle.done()